version: '3.0'

expectations:
  population_size: 10000

actions:


  generate_cohort_imd_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_imd_ethnicity
    outputs:
      highly_sensitive:
        cohort: output/input_imd_ethnicity.csv
  

  generate_cohort_1:
    # week 1 2019 to 21 2019 inclusive
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-12-31 to 2019-05-26 by week"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_cohort_2:
    # week 22 2019 to 42 2019 inclusive
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-05-27 to 2019-10-20 by week"
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  generate_cohort_3:
    # week  43 2019 to 11 2020 inclusive
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-10-21 to 2020-03-15 by week"
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv

  generate_cohort_4:
    # week 12 2020 to 32 2020 inclusive
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-03-16 to 2020-08-09 by week"
    outputs:
      highly_sensitive:
        cohort: output/inp*.csv

  generate_cohort_5:
    # week 33 2020 to week 53 2020 inclusive
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-08-10 to 2021-01-03 by week"
    outputs:
      highly_sensitive:
        cohort: output/in*.csv

  join_ethnicity_imd:
    run: python:latest python analysis/join_ethnicity_imd.py
    needs: [generate_cohort_1, generate_cohort_2, generate_cohort_3, generate_cohort_4, generate_cohort_5, generate_cohort_imd_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/i*.csv
   
  calculate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition
    needs: [join_ethnicity_imd]
    outputs:
      moderately_sensitive:
        measure: output/measure_*_rate.csv

  calculate_measures_demographics:
    run: python:latest python analysis/generate_measures_demographics.py
    needs: [join_ethnicity_imd]
    outputs:
      moderately_sensitive:
        csvs: output/measure_*_rate_*.csv
        

  standardise_and_plot:
    run: python:latest python analysis/time_series_plots.py
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        tables: output/*_rate.csv
        graph: output/time_series_plot.svg

  standardise_and_plot_demographics:
    run: python:latest python analysis/time_series_plots_demographics.py
    needs: [calculate_measures_demographics]
    outputs:
      moderately_sensitive:
        graph: output/time_series_plot_*.svg


